import json
from pathlib import Path

ROOT=Path(__file__).parent
PROJECT='8c5d0d86032348a0a6c85102fe97607e'
PAGE='98cfe13509bc1f5c'
def read(name):
    d=json.loads((ROOT/name).read_text(encoding='utf-8-sig'))
    assert d['ok'],name
    return d['result']
def emit(name,steps):
    (ROOT/name).write_text(json.dumps({'version':1,'meta':{'name':name,'project':PROJECT},'steps':steps},ensure_ascii=False,indent=2),encoding='utf-8')
def step(step_id,run,**flags):
    return {'id':step_id,'run':'sch '+run,'flags':dict(flags,doc=PAGE)}

positions={
'U1':(480,1370),'U3':(1090,1500),'U4':(420,870),'U5':(1050,860),'Y1':(1100,1200),
'C1':(950,1510),'C2':(1220,1510),'C3':(600,900),'R1':(600,800),
'R2':(950,760),'C4':(1200,920),'C5':(1200,750),'J3':(1280,840),
'C9':(120,1090),'C10':(220,1090),'C11':(320,1090),'C12':(420,1090),'C13':(520,1090),'C16':(620,1090),'C14':(720,1090),
'C17':(1000,1100),'C18':(1200,1100),'L2':(970,1280),
'R9':(220,550),'C15':(320,470),'SW2':(420,490),'R12':(620,550),'SW3':(780,470),'R10':(940,550),'R11':(1100,550),
'R13':(1140,380),'D3':(1020,380),'SW4':(630,360),
'L3':(400,230),'C20':(260,150),'C21':(520,150),'J4':(670,230),
'U2':(1780,1410),'L1':(1780,1520),'C6':(2040,1430),'C7':(2040,1370),'C8':(2040,1310),'R3':(1900,1220),'J2':(2190,1490),'SW1':(2190,1250),
'J1':(1790,870),'R4':(1570,700),'R5':(1790,700),'R6':(2090,950),'R7':(2090,870),'D1':(2220,950),'D2':(2220,870),'F1':(1600,610),'R8':(1780,610),
'R14':(1020,270),'R15':(1020,150),'C19':(1200,150)
}

if __name__=='__main__':
    main=read('repair-p1-live.json')
    full=read('repair-p1-full-before.json')
    power=read('repair-power-full-before.json')
    # Exact drawing-only deletion: keep all part instances, pin attributes, sheet.
    ids={c['primitiveId'] for c in main['components'] if c['componentType'] not in ('part','sheet')}
    ids|={w['primitiveId'] for w in main['wires']}
    # These magenta legacy frames were generated by our previous layout, not user content.
    ids|={x['primitiveId'] for x in full['pagePrimitives']['rectangles'] if x.get('Color')=='#AA00AA'}
    ids|={x['primitiveId'] for x in full['pagePrimitives']['texts'] if x.get('TextColor')=='#AA00AA'}
    emit('single-sheet-clean-drawing.json',[step('remove-old-wires-and-flags','prim-delete',ids=','.join(sorted(ids)))])
    moves=[]
    for c in main['components']:
        if c['componentType']=='part':
            assert c['designator'] in positions,c['designator']
            x,y=positions[c['designator']]
            moves.append(step('move-'+c['designator'],'modify',id=c['primitiveId'],x=x,y=y))
    emit('single-sheet-move-p1.json',moves)
    copies=[]
    for c in power['components']:
        if c['componentType']!='part': continue
        ref=c['designator']; x,y=positions[ref]
        dev=c['device']
        if ref=='L1': dev={'uuid':'5f542749891744148871d3719304a1eb','libraryUuid':'2cb3ad867dfa4740a0fbae81ea348a21'}
        assert len(dev['uuid'])==32,ref
        # The creation API negates supplied rotation. Match the measured instance.
        copies.append(step('copy-'+ref,'place',designator=ref,lib=dev['libraryUuid'],uuid=dev['uuid'],x=x,y=y,rotation=(-c['rotation'])%360))
    emit('single-sheet-copy-power.json',copies)
    expected={}
    for name in ['repair-p1-live.json','repair-power-live.json']:
        for c in read(name)['components']:
            if c['componentType']=='part':
                assert c['netlistAvailable'],c['designator']
                expected[c['designator']]={p['pinNumber']:p['net'] for p in c['pins']}
    (ROOT/'single-sheet-expected-before.json').write_text(json.dumps(expected,indent=2),encoding='utf-8')
    print('Prepared',len(moves),'preserved parts and',len(copies),'page transfers;',len(ids),'drawing primitives to replace')
